name: ci
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: download deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 1.22
      - name: check format
        run: deno fmt --check
      - name: lint
        run: deno lint
      - name: run tests
        run: deno test --allow-read --allow-write